name: Scala CI

on: [pull_request]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: sbt clean test
